language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
      dist: trusty
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: 3.8
      env: TOXENV=py38

before_install:
  - python --version
  - lsb_release -a
install:
  - pip install tox
  - tox --version
script: tox
notifications:
  email: false
